name: Test
on: push
jobs:
  Job1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Initialize
      run: |
        mkdir BuildResults
        mkdir BuildResults\KaosCombinatorics-Release
    - name: Build library
      run: |
        dotnet msbuild -nologo -restore -p:Configuration=Release Combinatorics
        copy Combinatorics\bin\Release\*.nupkg BuildResults\KaosCombinatorics-Release
    - name: Build standard suite
      run: dotnet msbuild -nologo -restore -p:Configuration=Release TestCore
    - name: Run standard suite
      run: dotnet test -c Release TestCore
    - uses: actions/upload-artifact@v1
      with:
        name: RunnerOutput-Release
        path: BuildResults\KaosCombinatorics-Release
