name: Test
on: push
jobs:
  Job1:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build standard suite
      run: dotnet msbuild -nologo -restore -p:Configuration=Debug TestCore
    - name: Run standard suite
      run: dotnet vstest TestCore\bin\Debug\netcoreapp3.1\TestCore.dll
